### ISSUE TITLE
update Electrs

### ISSUE THREAD

**Issue by tiero** [vulpemventures/docker-electrs#1]
@altafan

**Comment by ldub** [comment]
+1

need v0.6.1+  for embedded docker dns to work

**Comment by altafan** [comment]
we are using Blockstream/electrs and the latest version is the 0.4.1. :/
This fork is mandatory for Liquid, since the original version does not have support for the sidechain.

We could consider moving to romanz/electrs for the "mainchain" electrum server, but the use of docker dns would be restricted just to Bitcoin services, I guess.
